# Generated by Django 4.2 on 2023-04-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CENTRALIZADOR',
            fields=[
                ('IDCENTRALIZADOR', models.AutoField(primary_key=True, serialize=False)),
                ('CENTRALIZADOR', models.CharField(max_length=255)),
                ('PARENTID', models.IntegerField(default=0)),
                ('IDUSERREG', models.IntegerField(default=0)),
                ('ESTADO', models.BooleanField(default=True)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField(default=0)),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CENTRALIZADOR',
            },
        ),
        migrations.CreateModel(
            name='CONFREMEDY',
            fields=[
                ('IDCONFREMEDY', models.AutoField(primary_key=True, serialize=False)),
                ('IDATRIBUTO', models.CharField(max_length=255)),
                ('ATRIBUTO', models.CharField(max_length=255)),
                ('DEPENDENCIA1', models.CharField(max_length=255)),
                ('DEPENDENCIA2', models.CharField(max_length=255)),
                ('TIPO', models.CharField(max_length=50)),
                ('IDUSERREG', models.IntegerField(default=0)),
                ('ESTADO', models.BooleanField(default=True)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField(blank=True, null=True)),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CONF_REMEDY',
            },
        ),
        migrations.CreateModel(
            name='CONTROLITSM',
            fields=[
                ('IDCONTROLITSM', models.AutoField(primary_key=True, serialize=False)),
                ('IDCENTRALIZADOR', models.IntegerField()),
                ('URL', models.CharField(max_length=300)),
                ('HEAD', models.CharField(max_length=2000)),
                ('BODY', models.CharField(max_length=8000)),
                ('TIPO', models.CharField(max_length=50)),
                ('IDUSERREG', models.IntegerField(default=0)),
                ('ESTADO', models.BooleanField(default=True)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField(blank=True, null=True)),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
                ('PRIORIDAD', models.SmallIntegerField()),
                ('TICKETID', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'CONTROL_ITSM',
            },
        ),
        migrations.CreateModel(
            name='MATRIZPRIORIDAD',
            fields=[
                ('IDMATRIZ', models.AutoField(primary_key=True, serialize=False)),
                ('IMPACTO', models.SmallIntegerField(default=0)),
                ('URGENCIA', models.SmallIntegerField(default=0)),
                ('PRIORIDAD', models.SmallIntegerField(default=0)),
                ('TIPO', models.CharField(max_length=20)),
                ('OWNERGROUP', models.CharField(max_length=300)),
                ('OWNERGROUPID', models.CharField(max_length=300)),
                ('ESTADO', models.IntegerField(default=1)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField(blank=True, null=True)),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MATRIZ_PRIORIDAD',
            },
        ),
        migrations.CreateModel(
            name='MONITOR',
            fields=[
                ('IDMONITOR', models.AutoField(primary_key=True, serialize=False)),
                ('CLIENT', models.CharField(blank=True, max_length=100, null=True)),
                ('ALERTID', models.CharField(blank=True, max_length=255, null=True)),
                ('ALERTSTATE', models.CharField(blank=True, max_length=50, null=True)),
                ('TICKETID', models.CharField(blank=True, max_length=50, null=True)),
                ('TICKETSTATE', models.CharField(blank=True, max_length=50, null=True)),
                ('OWNERGROUP', models.CharField(blank=True, max_length=255, null=True)),
                ('PRIORITY', models.CharField(blank=True, max_length=255, null=True)),
                ('SYSLASTDATE', models.DateTimeField(auto_now=True)),
                ('SYSSTARTDATE', models.DateTimeField(auto_now_add=True)),
                ('URLTICKET', models.CharField(blank=True, max_length=255, null=True)),
                ('DISPOSITIVO', models.CharField(blank=True, max_length=255, null=True)),
                ('STATUS', models.BooleanField(default=True)),
                ('ESTADO', models.CharField(default='PENDIENTE', max_length=30)),
            ],
            options={
                'db_table': 'MONITOR',
            },
        ),
        migrations.CreateModel(
            name='OPCIONE',
            fields=[
                ('IDOPCION', models.AutoField(primary_key=True, serialize=False)),
                ('ATRIBUTO', models.CharField(max_length=512)),
                ('VALOR', models.CharField(max_length=512)),
                ('ICON', models.CharField(max_length=255)),
                ('URI', models.CharField(max_length=300)),
                ('PRIORIDAD', models.IntegerField()),
                ('PARENTID', models.IntegerField()),
                ('TIPOATRIBUTO', models.CharField(max_length=255)),
                ('IDUSERREG', models.IntegerField()),
                ('ESTADO', models.IntegerField(default=1)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField()),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
                ('VALOR1', models.CharField(max_length=512)),
                ('VALOR2', models.CharField(default='', max_length=255)),
                ('VALOR3', models.CharField(default='', max_length=255)),
                ('ENTERO1', models.IntegerField(default=0)),
                ('ENTERO2', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'OPCIONES',
            },
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('IDUSUARIO', models.AutoField(primary_key=True, serialize=False)),
                ('USUARIO', models.CharField(max_length=50)),
                ('PWD', models.BinaryField(max_length=8000)),
                ('NOMBRE', models.CharField(max_length=255)),
                ('APELLIDO', models.CharField(max_length=255)),
                ('CORREO', models.CharField(max_length=255)),
                ('TOKEN', models.CharField(max_length=255)),
                ('IDUSERREG', models.IntegerField()),
                ('ESTADO', models.IntegerField(default=1)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField()),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
                ('TELEFONO', models.CharField(default='', max_length=20)),
                ('IDAREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='monitor.opcione')),
                ('IDPERFIL_EMPLEADO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empleado', to='monitor.opcione')),
            ],
            options={
                'db_table': 'USUARIOS',
            },
        ),
        migrations.CreateModel(
            name='INVENTARIO',
            fields=[
                ('IDINVENTARIO', models.AutoField(primary_key=True, serialize=False)),
                ('CLIENT', models.CharField(max_length=255)),
                ('HOSTNAME', models.CharField(max_length=255)),
                ('IP', models.CharField(max_length=50)),
                ('ENTORNO', models.CharField(max_length=50)),
                ('ROL', models.CharField(max_length=50)),
                ('CRITICIDAD', models.CharField(max_length=20)),
                ('IDUSERREG', models.IntegerField(default=0)),
                ('ESTADO', models.BooleanField(default=True)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField()),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
                ('ALP', models.CharField(max_length=20)),
                ('IDLOGINITSM', models.CharField(max_length=20)),
                ('PROYECTO', models.CharField(max_length=255)),
                ('CAT1', models.CharField(max_length=255)),
                ('CAT2', models.CharField(max_length=255)),
                ('CAT3', models.CharField(max_length=255)),
                ('IDCONFREMEDY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.confremedy')),
            ],
            options={
                'db_table': 'INVENTARIO',
            },
        ),
        migrations.CreateModel(
            name='CENTRALIZADORPERFIL',
            fields=[
                ('IDCENTRALIZADORPERFIL', models.AutoField(primary_key=True, serialize=False)),
                ('PERFIL', models.CharField(max_length=255)),
                ('PARENTID', models.IntegerField(default=0)),
                ('IDUSERREG', models.IntegerField(default=0)),
                ('ESTADO', models.BooleanField(default=True)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField(default=0)),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
                ('IDCENTRALIZADOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.centralizador')),
                ('IDTOOL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.opcione')),
            ],
            options={
                'db_table': 'CENTRALIZADOR_PERFIL',
            },
        ),
        migrations.CreateModel(
            name='CENTRALIZADORDETALLE',
            fields=[
                ('IDCENTRALIZADORDETALLE', models.AutoField(primary_key=True, serialize=False)),
                ('AVANZADO', models.BooleanField(default=True)),
                ('URL', models.CharField(max_length=255)),
                ('HEAD', models.CharField(max_length=2000)),
                ('CONTENT', models.CharField(max_length=8000)),
                ('COMENTARIO', models.CharField(max_length=255)),
                ('TIPO', models.CharField(max_length=50)),
                ('IDUSERREG', models.IntegerField(default=0)),
                ('ESTADO', models.BooleanField(default=True)),
                ('SYSDATEREG', models.DateTimeField(auto_now_add=True)),
                ('IDUSERLAST', models.IntegerField(default=0)),
                ('SYSDATELAST', models.DateTimeField(auto_now=True)),
                ('IDCENTRALIZADORPERFIL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.centralizadorperfil')),
            ],
            options={
                'db_table': 'CENTRALIZADOR_DETALLE',
            },
        ),
        migrations.AddField(
            model_name='centralizador',
            name='IDCLIENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.opcione'),
        ),
    ]
