# Generated by Django 4.2 on 2023-04-25 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_alter_equipoip_id_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MONITOREOINVENTARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MONITOREADO', models.CharField(max_length=100)),
                ('METODO_MONITOREO', models.CharField(max_length=100)),
                ('VERSION_AGENTE', models.CharField(max_length=100)),
                ('EQUIPO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
            ],
            options={
                'db_table': 'MONITOREO_INVENTARIO',
            },
        ),
        migrations.CreateModel(
            name='WEBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBSERVACION', models.CharField(max_length=100)),
                ('TIPO', models.CharField(max_length=100)),
                ('MONITOREADO_DESDE', models.CharField(max_length=100)),
                ('INTERVALO', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'WEBS',
            },
        ),
        migrations.CreateModel(
            name='SERVICIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICIO_ASOCIADO', models.CharField(max_length=100)),
                ('COMMAND', models.CharField(max_length=100)),
                ('INTERVALO', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'SERVICIOS',
            },
        ),
        migrations.CreateModel(
            name='REDES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INTERFACES', models.CharField(max_length=100)),
                ('DESCRIPCION', models.CharField(max_length=100)),
                ('OBSERVACION', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'REDES',
            },
        ),
        migrations.CreateModel(
            name='NETWORK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROTOCOLO', models.CharField(max_length=100)),
                ('PORT', models.CharField(max_length=100)),
                ('INTERVALO', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'NETWORK',
            },
        ),
        migrations.CreateModel(
            name='INATIVIDADPROGRAMADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LUNES', models.CharField(max_length=100)),
                ('MARTES', models.CharField(max_length=100)),
                ('MIERCOLES', models.CharField(max_length=100)),
                ('JUEVES', models.CharField(max_length=100)),
                ('VIERNES', models.CharField(max_length=100)),
                ('SABADO', models.CharField(max_length=100)),
                ('DOMINGO', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'INATIVIDAD_PROGRAMADA',
            },
        ),
        migrations.CreateModel(
            name='FILESYSTEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('METRICA_DISCO', models.CharField(max_length=100)),
                ('UMBRAL_WANING', models.CharField(max_length=100)),
                ('UMBRAL_CRITICAL', models.CharField(max_length=100)),
                ('UMBRAL_FATAL', models.CharField(max_length=100)),
                ('INTERVALO_CAPTURA', models.CharField(max_length=100)),
                ('NOMBRE_UMBRAL', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'FILE_SYSTEM',
            },
        ),
        migrations.CreateModel(
            name='CPUMEMORIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFU_UMBRAL_WARNING', models.CharField(max_length=100)),
                ('MFU_UMBRAL_CRITICAL', models.CharField(max_length=100)),
                ('MFU_UMBRAL_FATAL', models.CharField(max_length=100)),
                ('MFU_INTEVALO_CAPTURA', models.CharField(max_length=100)),
                ('MFU_NOMBRE_UMBRAL', models.CharField(max_length=100)),
                ('SU_UMBRAL_WARNING', models.CharField(max_length=100)),
                ('SU_UMBRAL_CRITICAL', models.CharField(max_length=100)),
                ('SU_UMBRAL_FATAL', models.CharField(max_length=100)),
                ('SU_INTEVALO_CAPTURA', models.CharField(max_length=100)),
                ('SU_NOMBRE_UMBRAL', models.CharField(max_length=100)),
                ('CU_UMBRAL_WARNING', models.CharField(max_length=100)),
                ('CU_UMBRAL_CRITICAL', models.CharField(max_length=100)),
                ('CU_INTEVALO_CAPTURA', models.CharField(max_length=100)),
                ('CU_NOMBRE_UMBRAL', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'CPU_MEMORIA',
            },
        ),
        migrations.CreateModel(
            name='CAMBIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBSERVACION', models.CharField(max_length=100)),
                ('TIPO', models.CharField(max_length=100)),
                ('MONITOREADO_DESDE', models.CharField(max_length=100)),
                ('INTERVALO', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'CAMBIOS',
            },
        ),
        migrations.CreateModel(
            name='APLICACIONES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPO_MONITOREO', models.CharField(max_length=100)),
                ('NOMBRE_MODULO', models.CharField(max_length=100)),
                ('PATH', models.CharField(max_length=100)),
                ('DATA', models.CharField(max_length=100)),
                ('ALERTAS', models.CharField(max_length=100)),
                ('SEVERIDAD', models.CharField(max_length=100)),
                ('UMBRAL', models.CharField(max_length=100)),
                ('OWNER', models.CharField(max_length=100)),
                ('INTERVALO', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'APLICACIONES',
            },
        ),
        migrations.CreateModel(
            name='ALERTAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBSERVACION', models.CharField(max_length=100)),
                ('TIPO', models.CharField(max_length=100)),
                ('MONITOREADO_DESDE', models.CharField(max_length=100)),
                ('INTERVALO', models.CharField(max_length=100)),
                ('MONITOREO_INVENTARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoreo.monitoreoinventario')),
            ],
            options={
                'db_table': 'ALERTAS',
            },
        ),
    ]
